# Generated by Django 2.2.6 on 2019-10-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
